---
java:
  image: '${IMAGE_NAME}'
  ingressHost: ${SERVICE_FQDN}
  releaseNameOverride: ${RELEASE_NAME}
  environment:
    SERVICES__BOOKINGSAPIRESOURCEID: http://vh-bookings-api.staging.platform.hmcts.net

