#!/bin/sh

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3


# Get the current branch name 
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
# exstract a part of branch name with the VIH-XXX
 TRIMMED=$(echo $BRANCH_NAME | sed -e 's/.*\/*\(VIH-[0-9]\{4\}\).*/\1/')
# get the current commit message
currentmsg=$(cat "$COMMIT_MSG_FILE")

valid_mesg_regex="^(VIH-[0-9]{4} : )[a-zA-Z0-9._-]+$"
if [[ ! $currentmsg =~ $valid_mesg_regex ]]
then
    echo "${TRIMMED} : ${currentmsg} " > "$COMMIT_MSG_FILE"
fi




 