mode: ContinuousDelivery
ignore:
  sha: []
merge-message-formats: {}
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
commit-message-incrementing: Enabled
branches:
  main:
    regex: ^master$|^main$
    mode: ContinuousDelivery
    tag: staging
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    is-mainline: true
    pre-release-weight: 55000
  release:
    regex: ^releases?[/-]
    mode: ContinuousDelivery
    tag: ''
    increment: None
    source-branches: [ 'master', 'main', 'hotfix', 'release' ]
    is-release-branch: true
  feature:
    regex: ^features?[/-]|^VIH$
    mode: ContinuousDelivery
    tag: useBranchName
    increment: Inherit
    source-branches: [ 'develop', 'master', 'main', 'release', 'feature', 'hotfix' ]
  pull-request:
    regex: ^(pull|pull\-requests|pr)[/-]
    mode: ContinuousDelivery
    tag: PullRequest
    increment: Inherit
    tag-number-pattern: '[/-](?<number>\d+)[-/]'
    source-branches: [ 'develop', 'master', 'main', 'release', 'feature', 'hotfix' ]
  hotfix:
    regex: ^hotfix(es)?[/-]
    mode: ContinuousDelivery
    tag: hotfix
    increment: Patch
    track-merge-target: false
    source-branches: [ 'develop', 'main', 'support' ]