using BookingsApi.Domain;
using Microsoft.EntityFrameworkCore.Migrations;

namespace BookingsApi.DAL.Migrations
{
    public partial class AddRemainderNewVenuesForEnglandAndWales : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
              table: nameof(HearingVenue),
              columns: new[] { "Id", "Name" },
              values: new object[,]
              {
                    { 53, "Aberystwyth Justice Centre" },
                    { 54, "Aldershot Justice Centre" },
                    { 55, "Amersham Law Courts" },
                    { 56, "Aylesbury Crown Court" },
                    { 57, "Barkingside Magistrates Court" },
                    { 58, "Barnet Civil and Family Courts Centre" },
                    { 59, "Barnsley Law Courts" },
                    { 60, "Barnstaple Magistrates, County and Family Court" },
                    { 61, "Barrow-in-Furness County Court and Family Court" },
                    { 62, "Barrow-in-Furness Magistrates Court" },
                    { 63, "Basildon Combined Court" },
                    { 64, "Basildon Magistrates Court and Family Court" },
                    { 65, "Basingstoke County Court and Family Court" },
                    { 66, "Basingstoke Magistrates' Court" },
                    { 67, "Bath Law Courts (Civil and Family)" },
                    { 68, "Bedford County Court and Family Court" },
                    { 69, "Berwick upon Tweed Magistrates Court" },
                    { 70, "Beverley Magistrates Court and Hearing Centre" },
                    { 71, "Bexley Magistrates Court" },
                    { 72, "Bexleyheath Social Security and Child Support Tribunal" },
                    { 73, "Birkenhead County Court" },
                    { 74, "Birmingham Crown Court" },
                    { 75, "Birmingham Employment Tribunal" },
                    { 76, "Birmingham Immigration and Asylum Chamber" },
                    { 77, "Birmingham Magistrates Court" },
                    { 78, "Birmingham Social Security and Child Support Tribunal" },
                    { 79, "Birmingham Youth Court" },
                    { 80, "Blackburn Family Court" },
                    { 81, "Blackburn Magistrates Court" },
                    { 82, "Blackpool Family Court" },
                    { 83, "Blackpool Magistrates and Civil Court" },
                    { 84, "Blackwood Civil and Family Court" },
                    { 85, "Bodmin Law Courts" },
                    { 86, "Bolton Crown Court" },
                    { 87, "Bolton Magistrates Court" },
                    { 88, "Bolton Social Security and Child Support Tribunal" },
                    { 89, "Boston Magistrates Court" },
                    { 90, "Boston County Court and Family Court" },
                    { 91, "Bournemouth Crown Court" },
                    { 92, "Bournemouth Combined Court" },
                    { 93, "Bradford and Keighley Magistrates Court and Family Court" },
                    { 94, "Bradford Combined Court Centre" },
                    { 95, "Brentford County and Family Court" },
                    { 96, "Bridlington Magistrates Court and Hearing Centre" },
                    { 97, "Brighton County Court" },
                    { 98, "Brighton Hearing Centre" },
                    { 99, "Brighton Magistrates Court" },
                    { 100, "Bristol Crown Court" },
                    { 101, "Bristol Magistrates Court and Tribunals Hearing Centre" },
                    { 102, "Bromley County Court and Family Court" },
                    { 103, "Bromley Magistrates Court" },
                    { 104, "Burnley Combined Court Centre" },
                    { 105, "Burnley Magistrates Court" },
                    { 106, "Bury St Edmunds County Court and Family Court" },
                    { 107, "Caernarfon Justice Centre" },
                    { 108, "Cambridge County Court and Family Court" },
                    { 109, "Cambridge Crown Court" },
                    { 110, "Cambridge Magistrates Court" },
                    { 111, "Cannock Magistrates Court" },
                    { 112, "Canterbury Combined Court Centre" },
                    { 113, "Canterbury Magistrates Court" },
                    { 114, "Cardiff Crown Court" },
                    { 115, "Cardiff Magistrates Court" },
                    { 116, "Cardiff Social Security and Child Support Tribunal" },
                    { 117, "Carlisle Combined Court" },
                    { 118, "Carlisle Magistrates Court" },
                    { 119, "Carmarthen County Court and Family Court" },
                    { 120, "Central Criminal Court" },
                    { 121, "Central London County Court" },
                    { 122, "Central Family Court" },
                    { 123, "Central London Employment Tribunal" },
                    { 124, "Chelmsford Justice Centre" },
                    { 125, "Chelmsford Crown Court" },
                    { 126, "Chelmsford Magistrates Court and Family Court" },
                    { 127, "Cheltenham Magistrates Court" },
                    { 128, "Chester Civil and Family Justice Centre" },
                    { 129, "Chester Crown Court" },
                    { 130, "Chester Magistrates Court" },
                    { 131, "Chesterfield Justice Centre" },
                    { 132, "City of London Magistrates Court" },
                    { 133, "Clerkenwell and Shoreditch County Court and Family Court" },
                    { 134, "Colchester Magistrates Court and Family Court" },
                    { 135, "Court of Protection" },
                    { 136, "Coventry Combined Court Centre" },
                    { 137, "Coventry Magistrates Court" },
                    { 138, "Crawley Magistrates Court" },
                    { 139, "Crewe County Court and Family Court" },
                    { 140, "Crewe Magistrates Court" },
                    { 141, "Croydon County Court and Family Court" },
                    { 142, "Croydon Crown Court" },
                    { 143, "Croydon Employment Tribunal" },
                    { 144, "Croydon Magistrates Court" },
                    { 145, "Cwmbran Magistrates Court" },
                    { 146, "Darlington County Court and Family Court" },
                    { 147, "Darlington Magistrates Court and Family Court" },
                    { 148, "Dartford County Court and Family Court" },
                    { 149, "Derby Combined Court Centre" },
                    { 150, "Derby Social Security and Child Support Tribunal" },
                    { 151, "Derby Magistrates Court" },
                    { 152, "Doncaster Justice Centre North" },
                    { 153, "Doncaster Justice Centre South" },
                    { 154, "Dudley Magistrates Court" },
                    { 155, "Dudley County Court and Family Court" },
                    { 156, "Durham County Court and Family Court" },
                    { 157, "Durham Crown Court" },
                    { 158, "Ealing Magistrates Court" },
                    { 159, "East Berkshire Magistrates Court" },
                    { 160, "East London Family Court" },
                    { 161, "Edmonton County Court and Family Court" },
                    { 162, "Enfield Social Security and Child Support Tribunal" },
                    { 163, "Exeter Law Courts" },
                    { 164, "Folkestone Magistrates Court" },
                    { 165, "Gateshead Magistrates Court and Family Court" },
                    { 166, "Gateshead County Court and Family Court" },
                    { 167, "Gloucester Crown Court" },
                    { 168, "Gloucester and Cheltenham County and Family Court" },
                    { 169, "Great Yarmouth Magistrates Court and Family Court" },
                    { 170, "Great Grimsby Combined Court Centre" },
                    { 171, "Grimsby Magistrates Court and Family Court" },
                    { 172, "Guildford Crown Court" },
                    { 173, "Guildford County Court and Family Court" },
                    { 174, "Guildford Magistrates Court and Family Court" },
                    { 175, "Harmondsworth Tribunal Hearing Centre" },
                    { 176, "Harrogate Justice Centre" },
                    { 177, "Harrow Crown Court" },
                    { 178, "Hastings County Court and Family Court" },
                    { 179, "Hastings Magistrates Court" },
                    { 180, "Hatfield Magistrates Court" },
                    { 181, "Haverfordwest County Court and Family Court" },
                    { 182, "Haverfordwest Magistrates Court" },
                    { 183, "Hendon Magistrates Court" },
                    { 184, "Hereford Crown Court" },
                    { 185, "Hereford Justice Centre" },
                    { 186, "Hertford County Court and Family Court" },
                    { 187, "High Wycombe County Court and Family Court" },
                    { 188, "High Wycombe Magistrates Court and Family Court" },
                    { 189, "Highbury Corner Magistrates Court" },
                    { 190, "Horsham County Court and Family Court" },
                    { 191, "Horsham Magistrates Court" },
                    { 192, "Hove Trial Centre" },
                    { 193, "Huddersfield County Court and Family Court" },
                    { 194, "Hull and Holderness Magistrates Court and Hearing Centre" },
                    { 195, "Huntingdon Law Courts" },
                    { 196, "Inner London Crown Court" },
                    { 197, "Ipswich County Court and Family Hearing Centre" },
                    { 198, "Ipswich Crown Court" },
                    { 199, "Ipswich Magistrates Court" },
                    { 200, "Isle of Wight Combined Court" },
                    { 201, "Isleworth Crown Court" },
                    { 202, "Kidderminster Magistrates Court" },
                    { 203, "King's Lynn Crown Court" },
                    { 204, "Kingston upon Thames County Court and Family Court" },
                    { 205, "Kingston upon Thames Crown Court" },
                    { 206, "Kingston-upon-Hull Combined Court Centre" },
                    { 207, "Kirklees (Huddersfield) Magistrates Court and Family Court " },
                    { 208, "Lancaster Court House" },
                    { 209, "Lancaster Crown Court" },
                    { 210, "Land Registration" },
                    { 211, "Lavender Hill Magistrates Court" },
                    { 212, "Leeds Combined Court Centre" },
                    { 213, "Leeds District Probate Registry" },
                    { 214, "Leeds Employment Tribunal" },
                    { 215, "Leeds Magistrates Court and Family Court" },
                    { 216, "Leeds Social Security and Child Support Tribunal" },
                    { 217, "Leicester County Court and Family Court" },
                    { 218, "Leicester Crown Court" },
                    { 219, "Leicester Magistrates Court" },
                    { 220, "Leicester Tribunal Hearing Centre" },
                    { 221, "Lewes Combined Court Centre" },
                    { 222, "Leyland Family Hearing Centre" },
                    { 223, "Lincoln County Court and Family Court" },
                    { 224, "Lincoln Crown Court" },
                    { 225, "Lincoln Magistrates Court" },
                    { 226, "Liverpool Crown Court" },
                    { 227, "Liverpool District Probate Registry" },
                    { 228, "Liverpool and Knowsley Magistrates Court" },
                    { 229, "Liverpool Social Security and Child Support Tribunal" },
                    { 230, "Llandrindod Wells Magistrates and Family Court" },
                    { 231, "Llandudno Magistrates Court" },
                    { 232, "Llanelli Law Courts" },
                    { 233, "London (South) Employment Tribunal" },
                    { 234, "London Circuit Commercial Court" },
                    { 235, "Loughborough Court" },
                    { 236, "Luton and South Bedfordshire Magistrates Court" },
                    { 237, "Luton Crown Court" },
                    { 238, "Luton Justice Centre" },
                    { 239, "Maidstone Combined Court Centre" },
                    { 240, "Maidstone Magistrates Court" },
                    { 241, "Manchester Crown Court (Crown Square)" },
                    { 242, "Manchester Crown Court (Minshull St)" },
                    { 243, "Manchester Employment Tribunal" },
                    { 244, "Manchester Magistrates Court" },
                    { 245, "Mansfield Magistrates and County Court" },
                    { 246, "Margate Magistrates Court" },
                    { 247, "Mayor's and City of London Court" },
                    { 248, "Medway Magistrates Court and Family Court" },
                    { 249, "Medway County Court and Family Court" },
                    { 250, "Merthyr Tydfil Combined Court Centre" },
                    { 251, "Mid and South East Northumberland Law Courts" },
                    { 252, "Milton Keynes County Court and Family Court" },
                    { 253, "Milton Keynes Magistrates Court and Family Court" },
                    { 254, "Mold Justice Centre (Mold Law Courts)" },
                    { 255, "Newcastle Civil & Family Courts and Tribunals Centre" },
                    { 256, "Newcastle District Probate Registry" },
                    { 257, "Newcastle Moot Hall" },
                    { 258, "Newcastle upon Tyne Crown Court and Magistrates Court" },
                    { 259, "Newport (South Wales) County Court and Family Court" },
                    { 260, "Newport (South Wales) Crown Court" },
                    { 261, "Newport (South Wales) Magistrates Court" },
                    { 262, "Newton Abbot Magistrates Court" },
                    { 263, "Newton Aycliffe Magistrates Court" },
                    { 264, "North Somerset Magistrates Court" },
                    { 265, "North Staffordshire Justice Centre" },
                    { 266, "North Tyneside Magistrates Court" },
                    { 267, "Northampton Crown, County and Family Court" },
                    { 268, "Northampton Magistrates Court" },
                    { 269, "Northampton Social Security and Child Support Tribunal" },
                    { 270, "Norwich Combined Court Centre" },
                    { 271, "Norwich Magistrates Court and Family Court" },
                    { 272, "Norwich Social Security and Child Support Tribunal" },
                    { 273, "Nottingham County Court and Family Court" },
                    { 274, "Nottingham Crown Court" },
                    { 275, "Nottingham Magistrates Court" },
                    { 276, "Nottingham Social Security and Child Support Tribunal" },
                    { 277, "Oxford Magistrates Court" },
                    { 278, "Oxford Combined Court Centre" },
                    { 279, "Peterborough Combined Court Centre" },
                    { 280, "Peterborough Magistrates Court" },
                    { 281, "Peterlee Magistrates Court" },
                    { 282, "Plymouth Combined Court" },
                    { 283, "Plymouth Magistrates Court" },
                    { 284, "Pontypridd County Court and Family Court" },
                    { 285, "Poole Magistrates Court" },
                    { 286, "Portsmouth Combined Court Centre" },
                    { 287, "Portsmouth Magistrates Court" },
                    { 288, "Prestatyn Justice Centre" },
                    { 289, "Preston Combined Court Centre" },
                    { 290, "Preston Crown Court and Family Court (Sessions House)" },
                    { 291, "Preston Magistrates Court" },
                    { 292, "Reading County Court and Family Court" },
                    { 293, "Reading Crown Court" },
                    { 294, "Reading Magistrates Court and Family Court" },
                    { 295, "Reading Tribunal Hearing Centre" },
                    { 296, "Redditch Magistrates Court" },
                    { 297, "Reedley Family Hearing Centre" },
                    { 298, "Residential Property Tribunal" },
                    { 299, "Romford County Court and Family Court" },
                    { 300, "Romford Magistrates Court (formerly Havering Magistrates' Court)" },
                    { 301, "Salisbury Law Courts" },
                    { 302, "Scarborough Justice Centre" },
                    { 303, "Sefton Magistrates Court " },
                    { 304, "Sevenoaks Magistrates Court and Family Court" },
                    { 305, "Sheffield Combined Court Centre" },
                    { 306, "Sheffield Designated Family Court" },
                    { 307, "Shrewsbury Crown Court" },
                    { 308, "Skipton County Court and Family Court" },
                    { 309, "Skipton Magistrates Court" },
                    { 310, "Slough County Court and Family Court" },
                    { 311, "Snaresbrook Crown Court" },
                    { 312, "South Tyneside County Court and Family Court" },
                    { 313, "South Tyneside Magistrates Court" },
                    { 314, "Southend County Court and Family Court" },
                    { 315, "Southend Crown Court" },
                    { 316, "Southend Magistrates Court" },
                    { 317, "Southwark Crown Court" },
                    { 318, "St Albans Crown Court" },
                    { 319, "St Albans Magistrates Court" },
                    { 320, "St Helens County Court and Family Court" },
                    { 321, "Stafford Combined Court Centre" },
                    { 322, "Staines County Court and Family Court" },
                    { 323, "Staines Magistrates Court and Family Court" },
                    { 324, "Stevenage Magistrates Court" },
                    { 325, "Stockport County Court and Family Court" },
                    { 326, "Stockport Magistrates Court" },
                    { 327, "Stoke-on-Trent Combined Court" },
                    { 328, "Sunderland County, Family, Magistrates and Tribunal Hearings" },
                    { 329, "Sutton Social Security and Child Support Tribunal" },
                    { 330, "Swansea Crown Court" },
                    { 331, "Swansea Magistrates Court" },
                    { 332, "Swindon Combined Court" },
                    { 333, "Swindon Magistrates Court" },
                    { 334, "Tameside Magistrates Court" },
                    { 335, "Taunton Combined Court" },
                    { 336, "Taunton Magistrates Court, Tribunals and Family Hearing Centre" },
                    { 337, "Teesside Magistrates Court" },
                    { 338, "Teesside Combined Court Centre" },
                    { 339, "Telford County Court and Family Court" },
                    { 340, "Telford Magistrates Court" },
                    { 341, "Thames Magistrates Court" },
                    { 342, "Torquay and Newton Abbot County Court and Family Court" },
                    { 343, "Truro Combined Court" },
                    { 344, "Truro Magistrates Court" },
                    { 345, "Uxbridge County Court and Family Court" },
                    { 346, "Uxbridge Magistrates Court" },
                    { 347, "Wakefield Civil and Family Justice Centre" },
                    { 348, "Walsall County and Family Court" },
                    { 349, "Walsall Magistrates Court" },
                    { 350, "Wandsworth County Court and Family Court" },
                    { 351, "Warrington Crown Court" },
                    { 352, "Warrington Magistrates Court" },
                    { 353, "Warwick Combined Court" },
                    { 354, "Watford County Court and Family Court" },
                    { 355, "Watford Tribunal Hearing Centre" },
                    { 356, "Wellingborough Magistrates Court" },
                    { 357, "Welshpool Magistrates Court" },
                    { 358, "West Cumbria Courthouse" },
                    { 359, "West Hampshire (Southampton) Magistrates Court" },
                    { 360, "West London Family Court" },
                    { 361, "Westminster Magistrates Court" },
                    { 362, "Weymouth Combined Court" },
                    { 363, "Wigan and Leigh Magistrates Court" },
                    { 364, "Wigan County Court and Family Court" },
                    { 365, "Willesden County Court and Family Court" },
                    { 366, "Willesden Magistrates Court" },
                    { 367, "Wimbledon Magistrates Court" },
                    { 368, "Winchester Combined Court Centre" },
                    { 369, "Wirral Magistrates Court" },
                    { 370, "Wolverhampton Combined Court Centre" },
                    { 371, "Wolverhampton Magistrates Court" },
                    { 372, "Wood Green Crown Court" },
                    { 373, "Woolwich Crown Court" },
                    { 374, "Worcester Combined Court" },
                    { 375, "Worcester Justice Centre" },
                    { 376, "Worthing County Court and Family Court" },
                    { 377, "Worthing Magistrates Court" },
                    { 378, "Wrexham County and Family Court" },
                    { 379, "Wrexham Magistrates Court" },
                    { 380, "Yeovil County, Family and Magistrates Court" },
                    { 381, "York County Court and Family Court" },
                    { 382, "York Crown Court" },
                    { 383, "York Magistrates Court and Family Court" },
                    { 384, "War and Pension Tribunal" }
              });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            for (int hearingVenueId = 53; hearingVenueId <= 384; hearingVenueId++)
            {
                migrationBuilder.DeleteData(nameof(HearingVenue), "Id", hearingVenueId);
            }
        }
    }
}
